import binary_operations as bin
number1 = int(input("Введите первое число "))
direct1 = bin.direct_code(number1)
print(f'Direct code: {direct1}')
inverse1 = bin.inverse_code(direct1.copy())
print(f'Inverse code: {inverse1}')
additional1 = bin.additional_code(inverse1.copy())
print(f'Additional code: {additional1}')
number2 = int(input("Введите второе число "))
direct2 = bin.direct_code(number2)
print(f'Direct code: {direct2}')
inverse2 = bin.inverse_code(direct2.copy())
print(f'Inverse code: {inverse2}')
additional2 = bin.additional_code(inverse2.copy())
print(f'Additional code: {additional2}')
print("=====================")
print(f'Binary sum: {bin.additional_sum(additional1.copy(), additional2.copy())}, int: {number1+number2}')
print(f'Binary minus: {bin.additional_subtraction(additional1.copy(), additional2.copy())}, int: {number1-number2}')
print(f'Binary multiplication{bin.direct_multiplication(direct1.copy(), direct2.copy())}, int: {number1*number2}')
quotient, remainder = bin.binary_division(direct1.copy(), direct2.copy())
print(f'Quotient: {quotient}, Remainder: {remainder}, int: {number1/number2}')
float_numb1 = float(input("Введите первое число "))
bin1 = bin.float_to_binary(float_numb1)
iee754first = bin.binary_to_ieee754(bin1)
iee754first.print_info()
float_numb2 = float(input("Введите второе число "))
bin2 = bin.float_to_binary(float_numb2)
iee754second = bin.binary_to_ieee754(bin2)
iee754second.print_info()
print(f'Integer result: {float_numb1/float_numb2}')
bin.ieee754_sum(iee754first, iee754second)